#!/usr/bin/env python
# coding: utf8

from ubackup.args import *
from ubackup.conf import *
from ubackup.backup import *
from ubackup.snapshot import *

# processing command line arguments
arg = readargs()

if arg.version:
    print "ubackup v0.2.3"
    sys.exit(0)

# if option "verbose" is switched on, than switching on flag "debug"
if arg.v:
    debug = True
else:
    debug = None

if debug:
    print "Command line arguments: %s" % arg

# reading configuration
conf = ItemConfig(ReadConf(arg.conf, debug))

# show snapshot list
snapshotList(arg)

if arg.d:
    print "\nDRY RUN MODE!"

# showing configuration
if arg.s:
    showConfig(conf,arg)

# removing snapshot
if arg.snapshot_rm:
    snapshotRm(arg)

# launching backup process
if not arg.n:
    runBackup(conf, arg, debug)

# creating snapshot
if arg.snapshot:
    createSnapshot(conf, arg, debug)

# rotating snapshots
if arg.snapshot_rotate:
    rotateSnapshot(conf, arg)
