#!/usr/bin/env python
# coding: utf8

from lib.args import *
from lib.conf import *
from lib.backup import *
from lib.snapshot import *

debug = None

# обрабатываем аргументы командной строки
arg = readargs()
if debug:
    print "Аргументы: %s" % arg

# читаем конфигурацию
if not arg.install_config:
    conf = ItemConfig(ReadConf(arg.conf))

# Инсталлируем новую конфигурацию
installConfig(arg)
# выводим список снапшотов
snapshotList(arg)
if arg.d:
    print "\nDRY RUN MODE!"
# Удаляем снапшот
snapshotRm(arg)
# выводим конфигурацию
showConfig(conf,arg)
# запускаем процесс бэкапа
runBackup(conf, arg)
# создаем снапшот
createSnapshot(conf, arg, debug)
# удаляем старые снапшоты
rotateSnapshot(conf, arg)
