#!/usr/bin/env python
# coding: utf8

from lib.args import *
from lib.conf import *
from lib.backup import *
from lib.snapshot import *

debug = None

# processing the command line arguments
arg = readargs()
if debug:
    print "Аргументы: %s" % arg

# reading the configuration
if not arg.install_config:
    conf = ItemConfig(ReadConf(arg.conf))

# installing the new configuration
installConfig(arg)
# show snapshot list
snapshotList(arg)
if arg.d:
    print "\nDRY RUN MODE!"
# removing snapshot
snapshotRm(arg)
# showing configuration
showConfig(conf,arg)
# launching backup process
runBackup(conf, arg)
# creating snapshot
createSnapshot(conf, arg, debug)
# rotating snapshots
rotateSnapshot(conf, arg)
