#!/usr/bin/env python
# coding: utf8

from lib.args import *
from lib.conf import *
from lib.backup import *
from lib.snapshot import *

debug = None

# processing the command line arguments
arg = readargs()
if debug:
    print "Command line arguments: %s" % arg

# reading the configuration
if not arg.install_config:
    conf = ItemConfig(ReadConf(arg.conf, debug))

# installing the new configuration
installConfig(arg)

# show snapshot list
snapshotList(arg)

if arg.d:
    print "\nDRY RUN MODE!"

# showing configuration
if arg.s:
    showConfig(conf,arg)

# removing snapshot
if arg.snapshot_rm:
    snapshotRm(arg)

# launching backup process
if not arg.n:
    runBackup(conf, arg)

# creating snapshot
if arg.snapshot:
    createSnapshot(conf, arg, debug)

# rotating snapshots
if arg.snapshot_rotate:
    rotateSnapshot(conf, arg)
